CREATE DATABASE EHAHC;

use EHAHC;

CREATE TABLE Student (
Curtin_ID INT PRIMARY KEY,
Password VARCHAR(255) NOT NULL,
Student_name VARCHAR(100) NOT NULL,
Student_email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Chat_history (
Chat_ID INT AUTO_INCREMENT PRIMARY KEY, 
Use_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
Student_input TEXT NOT NULL, 
Bot_answer TEXT NOT NULL, 
Curtin_ID INT, 
FOREIGN KEY (Curtin_ID) REFERENCES Student(Curtin_ID) ON DELETE CASCADE
);